server:
  port: 8081
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/Peoplist'
    username: 'postgres'
    password: 'Nic3993.'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
    show-sql: true